// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbflpufksubnqegwqttr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZmxwdWZrc3VibnFlZ3dxdHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDQzOTEsImV4cCI6MjA2MDQ4MDM5MX0.y9XCVaxeeLNBtvGM-BrO626qZTLc_wdrC-6uQhvJZr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);